version: "3.3"
services:
  redis:
    image: redis/redis-stack:7.2.0-v6
    ports:
      - 6379:6379
      - 8001:8001
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
